### ISSUE TITLE
Forward same request to a service in every namespaces

### ISSUE THREAD

**Issue by bcouetil** [webhookrelay/webhookrelay-operator#23]
Hello, thank you for maintaining this tool 😊 

My use case is forwarding the request to a service in every namespaces.

I guess I could create a single `WebhookRelayForward` with multiple outputs like this :

```
      outputs:
        - name: business-backend-ns1
          destination: http://business-backend.ns1.svc.cluster.local
          internal: true
          lockPath: false
        - name: business-backend-ns2
          destination: http://business-backend.ns2.svc.cluster.local
          internal: true
          lockPath: false
```

But it means being aware of every namespaces at once, and mines are dynamic (these are ephemeral environments which all needs the requests).

Do I have another solution ? would it work if I created the same object in each namespace ; would it merge the redirection to do all, or would it be overriden each time by the latest ?

Thanks in advance for any input 🙏
