### ISSUE TITLE
Help to configure atlantis on internal Kubernetes with Webhook Relay

### ISSUE THREAD

**Issue by leandromoreirati** [webhookrelay/webhookrelay-operator#24]
Is using this article to configure Webhook relay for my atlantis lab on kubernetes.

I did folow all intructions but when I configured `WebhookRelayForward`, I received the follwoing error:

```json
{"level":"error","ts":1688430599.769275,"logger":"controller_webhookrelayforward","msg":"failed to create input","Request.Namespace":"atlantis","Request.Name":"forward-to-atlantis","bucket_name":"github-to-atlantis","bucket_id":"c28be0c1-1fe0-4300-b970-8495236b56ec","error":"HTTP status 402: feature not available for your subscription","errorVerbose":"HTTP status 402: feature not available for your subscription\ngithub.com/webhookrelay/webhookrelay-go.(*API).makeRequestWithAuthTypeAndHeaders\n\tgithub.com/webhookrelay/webhookrelay-go@v0.3.1/webhookrelay.go:207\ngithub.com/webhookrelay/webhookrelay-go.(*API).makeRequestWithAuthType\n\tgithub.com/webhookrelay/webhookrelay-go@v0.3.1/webhookrelay.go:119\ngithub.com/webhookrelay/webhookrelay-go.(*API).makeRequest\n\tgithub.com/webhookrelay/webhookrelay-go@v0.3.1/webhookrelay.go:111\ngithub.com/webhookrelay/webhookrelay-go.(*API).CreateInput\n\tgithub.com/webhookrelay/webhookrelay-go@v0.3.1/inputs.go:134\ngithub.com/webhookrelay/webhookrelay-operator/pkg/controller/webhookrelayforward.(*ReconcileWebhookRelayForward).ensureBucketInputs\n\tgithub.com/webhookrelay/webhookrelay-operator/pkg/controller/webhookrelayforward/sync_inputs.go:44\ngithub.com/webhookrelay/webhookrelay-operator/pkg/controller/webhookrelayforward.(*ReconcileWebhookRelayForward).ensureRoutingConfiguration\n\tgithub.com/webhookrelay/webhookrelay-operator/pkg/controller/webhookrelayforward/webhookrelayforward_routing_engine.go:30\ngithub.com/webhookrelay/webhookrelay-operator/pkg/controller/webhookrelayforward.(*ReconcileWebhookRelayForward).Reconcile\n\tgithub.com/webhookrelay/webhookrelay-operator/pkg/controller/webhookrelayforward/webhookrelayforward_controller.go:150\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tsigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90\nruntime.goexit\n\truntime/asm_amd64.s:1594","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/webhookrelay/webhookrelay-operator/pkg/controller/webhookrelayforward.(*ReconcileWebhookRelayForward).ensureBucketInputs\n\tgithub.com/webhookrelay/webhookrelay-operator/pkg/controller/webhookrelayforward/sync_inputs.go:46\ngithub.com/webhookrelay/webhookrelay-operator/pkg/controller/webhookrelayforward.(*ReconcileWebhookRelayForward).ensureRoutingConfiguration\n\tgithub.com/webhookrelay/webhookrelay-operator/pkg/controller/webhookrelayforward/webhookrelayforward_routing_engine.go:30\ngithub.com/webhookrelay/webhookrelay-operator/pkg/controller/webhookrelayforward.(*ReconcileWebhookRelayForward).Reconcile\n\tgithub.com/webhookrelay/webhookrelay-operator/pkg/controller/webhookrelayforward/webhookrelayforward_controller.go:150\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tsigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"}
```

My `webhook-relay-operator.yaml`

```yaml
replicaCount: 1

image:
  repository: webhookrelay/webhookrelay-operator
  pullPolicy: Always
  tag: "0.6.0"

credentials:
  key: my-key
  secret: my-secret

httpsProxy: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "webhookrelay-operator"

crd:
  create: false

rbac:
  create: true

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8383"

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
```

My webhook-atlantis.yaml

```yaml
apiVersion: forward.webhookrelay.com/v1
kind: WebhookRelayForward
metadata:
  name: forward-to-atlantis
  namespace: atlantis
spec:
  buckets:
  - name: github-to-atlantis
    inputs:
    - name: public-endpoint
      description: "Endpoint for GitHub"
      responseBody: "OK"
      responseStatusCode: 200
    outputs:
    - name: atlantis-pod
      destination: http://runatlantis.atlantis.svc.cluster.local # My atlantis service internal URL.
```
When I perform any PR on dashboard of webhook relay:

![image](https://github.com/webhookrelay/webhookrelay-operator/assets/30784301/892c25ed-b773-4289-b9da-7cb05c7756af)

Could you help me please?
